### ISSUE TITLE
Add a branch.

### ISSUE THREAD

**Issue by trych** [basiljs/examples#1]
@b-g 
Hi, sorry, could you also add a master branch to this, I seem to be unable to push to this repo, when it's entirely empty. Maybe just add an empty README.md as well, just to be on the safe side.

Thanks!

**Comment by b-g** [comment]
@trych Sorry, my bad! Done!

**Comment by trych** [comment]
@b-g 
Hm, I still have no write access. To avoid working from a fork, could you give me write access to the repo. Sorry for the trouble, I had no idea, that there are a few more steps necessary.

**Comment by b-g** [comment]
@trych Sorry! My bad II! Note to self: add basil core team to repo once created.
